### PR TITLE
add err check for sb.Finalize that was un-checked potentially causing issues

### PR DESCRIPTION
**Pull request by thomasmodeneis**
Hi,

I was reading up the code on the Tendermint backend and noticed a small issue that probably escaped from your eye. So I opened a small PR in order to contribute back to this amazing project! 

Please let me know if it is of any relevance to you or not.

### CODE REVIEW

**Review by aneequesafdar — APPROVED** [review]
LGTM

**Comment by yazzaoui** [comment]
Hi @thomasmodeneis, good spot! Although I think `Finalize` shouldn't fail if all the transactions were valid.
Thanks :+1:

**Review by yazzaoui — APPROVED** [review]

**Comment by piersy** [comment]
Hi @thomasmodeneis thanks for contributing!

We are having a problem with our github actions which have not been triggered for this PR. I think the problem could be that we run actions for PR's on our develop branch, but when you opened this PR you opened it against master and my switching the base branch to develop did not generate a new github actions PR event for the develop branch.

Could you try closing this PR and opening a new one against develop?

**Comment by thomasmodeneis** [comment]
> Hi @thomasmodeneis thanks for contributing!
> 
> We are having a problem with our github actions which have not been triggered for this PR. I think the problem could be that we run actions for PR's on our develop branch, but when you opened this PR you opened it against master and my switching the base branch to develop did not generate a new github actions PR event for the develop branch.
> 
> Could you try closing this PR and opening a new one against develop?

Sure, I can also try amend a small change on the log that will trigger the build most likely

**Pull request closed without merging**
