### PR TITLE
Prevent unintended test runs in ci

### PR DESCRIPTION
**Pull request by piersy**
When using a github actions matrix to run tests we were specifying
specific tests to run by name. Using this approach 'go test' will run
all tests with a matching prefix, which  in our case was causing us to
run tests more than once.

For example the following 2 matrix entries would cause
TestTendermintMajorityExternalUsersFullyConnected to be executed on each
run.

  TestTendermintMajorityExternalUsers,
  TestTendermintMajorityExternalUsersFullyConnected,

This commit updates the matching regex to match the word boundaries at
the beginning and end of the test name so that we only run the specified
test.

### CODE REVIEW

**Comment by aneequesafdar** [comment]
How did you find out that the tests were being run multiple times? Also, base on this https://www.regular-expressions.info/wordboundaries.html I am not sure how word boundaries are helping because a you would not be able to search for a specific word in a camel case string.

**Comment by piersy** [comment]
@aneequesafdar When I was investigating the intermittent test failures #619 looking at the logs I saw that actually in the ci failures for TestTendermintMajorityExternalUsers they were in fact failing because TestTendermintMajorityExternalUsersFullyConnected was failing.

Capital letters are not word boundaries.

The definition from the page you linked is.

> * Before the first character in the string, if the first character is a word character.
> * After the last character in the string, if the last character is a word character.
> * Between two characters in the string, where one is a word character and the other is not a word character.

These word boundaries are occurring at the beginning and end of the string. There are no word boundaries inside the test names because test names are made purely of word characters.

**Comment by aneequesafdar** [comment]
After discussing with @piersy I understood the matrix is used as a list to enumerate all the local e2e tests we want to run as separate parallel jobs, however, it is the `go` command which performs the match on regex test cases name present in the package which causes the `go test` command to run the test multiple times if a prefix is shared by multiple tests.

**Comment by piersy** [comment]
I'm closing this because it would be made redundant by the work I have been doing to speed up Ci

**Pull request closed without merging**
