### PR TITLE
Test proposer selection algorithms

### PR DESCRIPTION
**Pull request by JekaMas**
Introduces mocks and mock generation

### CODE REVIEW

**Comment by shapeshed** [comment]
This looks great. One question is how mocks are updated. I've seen regular problems with mocks not being kept up to date with interfaces. Is this a manual process?

**Comment by shapeshed** [comment]
Some linting errors to resolve on this build :smiley:

**Comment by JekaMas** [comment]
All mocks are generated by code generator 'gomock'. You can see 'mock-gen' command in the make file.
I think it's better not to generate mocks at CI, but run regeneration manually if needed and commit updated mocks. It helps to control changes, if you had changed an interface, your tests wouldn't compile and you had to regenerate mocks and fix tests.
@shapeshed

**Comment by shapeshed** [comment]
> I think it's better not to generate mocks at CI, but run regeneration manually if needed and commit updated mocks. It helps to control changes, if you had changed an interface, your tests wouldn't compile and you had to regenerate mocks and fix tests.

Yup agree.

**Pull request merged**
