### PR TITLE
Tiny fix in README.

### PR DESCRIPTION
**Pull request by flofrie**

### CODE REVIEW

**Comment by piersy** [comment]
@flofrie Thanks!

**Review by Jason-Zhangxin-Chen — APPROVED** [review]

**Comment by flofrie** [comment]
Thanks @Jason-Zhangxin-Chen . Need another approval.

**Comment by piersy** [comment]
@flofrie I'm wondering how you made this PR, did you simply edit the file on github and then click to make a PR from the change? The reason I ask is that our CI checks are hanging because the source for this PR is `unknown repository` which is not something I was aware could happen.

**Comment by flofrie** [comment]
Ah, sorry, yes, I did. What shall I do to fix it?

**Comment by piersy** [comment]
> Ah, sorry, yes, I did. What shall I do to fix it?

Hi @flofrie no need to do anything, we need to update our github actions workflow to handle PRs from `unknown repository`.

**Review by aneequesafdar — APPROVED** [review]

**Comment by flofrie** [comment]
Thank you @aneequesafdar for approving. I just found I can't merge because I don't have write access. Someone, please?

**Comment by aneequesafdar** [comment]
@flofrie Until the test pass no one can force merge except @yazzaoui

**Pull request merged**
